// Generated by CoffeeScript 1.4.0
(function() {
  var Api, Classifier, TopBar, User, api, classifier, topBar, _ref;

  if ((_ref = window.app) == null) {
    window.app = {};
  }

  Api = zooniverse.Api;

  api = new Api({
    project: 'cancer_gene_runner'
  });

  TopBar = zooniverse.controllers.TopBar;

  topBar = new TopBar;

  topBar.el.appendTo(document.body);

  Classifier = app.controllers.Classifier;

  classifier = new Classifier;

  classifier.el.appendTo(document.body);

  User = zooniverse.models.User;

  User.fetch();

  window.app.main = {
    api: api,
    topBar: topBar,
    classifier: classifier
  };

}).call(this);
