// Generated by CoffeeScript 1.4.0
(function() {
  var _base, _ref, _ref1;

  if ((_ref = window.app) == null) {
    window.app = {};
  }

  if ((_ref1 = (_base = window.app).views) == null) {
    _base.views = {};
  }

  window.app.views.Classifier = '<div class="subject">\n  <div class="loader">\n    <strong>Loading...</strong>\n  </div>\n\n  <svg width="100%" height="100%">\n    <path d="M0,0" fill="transparent" stroke="black" stroke-width="1" />\n  </svg>\n</div>\n\n<div class="controls">\n  <span class="classify">\n    <label><input type="checkbox" name="suspicious" /> Suspicious!</label>\n    <button name="submit">Submit</button>\n  </span>\n\n  <span class="move-on">\n    <button name="next">Next</button>\n  </span>\n</div>';

}).call(this);
